name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache pnpm
        uses: suimenkathemove/pnpm-cache-action@v1.0.0
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Check
        run: pnpm tsc

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache pnpm
        uses: suimenkathemove/pnpm-cache-action@v1.0.0
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Lint
        run: pnpm lint

  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache pnpm
        uses: suimenkathemove/pnpm-cache-action@v1.0.0
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Unit Test
        run: pnpm test

  build-storybook:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache pnpm
        uses: suimenkathemove/pnpm-cache-action@v1.0.0
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build Storybook
        run: pnpm build-storybook
