name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-storybook:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache pnpm
        uses: suimenkathemove/pnpm-cache-action@v1.0.0
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          install_command: pnpm install
          build_command: pnpm build-storybook
          path: storybook-static
          checkout: false
